spring:
  application:
    name: OldBask
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/old_bask_db?serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto

wechat:
  appid: "1233"
  secret: "222"